WebAppAsa/Models/FeverTemp.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppAsa.Models
{
    public class FeverTemp
    {
        public static string TestForFever(float temperature)
        {
            //double dubbleTemp = new double();
            
            return (temperature > 37) ? "Doctor Vader says you have fever...have a cookie" : "Doctor Vader says you don't have any fever...so no cookie";
        }
    }

}

WebAppAsa/Models/GameRandom.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppAsa.Models
{
    public class GameRandom
    {
        public static string MatchGuess(int guess, int rnd)
        {
            if (guess < rnd)
            {
                return "Higher!";
            }
            else if (guess > rnd)
            {
                return "Lower!";
            }
            else
            {
                return "Yes!! You won!";
            }
        }
        public static int GetRandom(int max)
        {
            Random rnd = new Random();
            return rnd.Next(1, max);
        }
    }
}

WebAppAsa/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppAsa.Controllers
{
    public class DoctorController : Controller
    {
        [HttpPost]
        public IActionResult FeverCheck(float temp)
        {
            if (temp != 0)
            {

                ViewBag.Msg = Models.FeverTemp.TestForFever(temp);
                return View();
            }
            else
            {
                ViewBag.Msg = "Pls enter your temperaure and then hit Submit";
                return View();
            }
        }
        [HttpGet]
        public IActionResult FeverCheck()
        {
            return View();
        }

    }
}

WebAppAsa/Controllers/GameController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppAsa.Models;

namespace WebAppAsa.Controllers
{
    public class GameController : Controller
    {
        [HttpPost]
        public IActionResult GuessingGame(int userGuess)
        {
            if (!(string.IsNullOrEmpty(HttpContext.Session.GetString("intRnd")) || userGuess <= 0 || userGuess >= 100))
            {
                int storedRnd = (int)HttpContext.Session.GetInt32("intRnd");
                string respons = GameRandom.MatchGuess(Convert.ToInt32(userGuess), storedRnd);
                ViewBag.Msg = respons;
            }
            else
            {
                ViewBag.Msg = "Enter a number between 1 and 100 and Submit";
            }
            return View();
        }

        [HttpGet]
        public IActionResult GuessingGame()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("intRnd")))
            {
                int getRnd = GameRandom.GetRandom(100);
                HttpContext.Session.SetInt32("intRnd", getRnd);
                ViewBag.Rnd = getRnd;
            }
            else 
            {
                ViewBag.Rnd = HttpContext.Session.GetInt32("intRnd");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Reset()
        {
            int getRnd = GameRandom.GetRandom(100);
            HttpContext.Session.SetInt32("intRnd", getRnd);
            ViewBag.Rnd = getRnd;
            return RedirectToAction(nameof(GuessingGame));
        }
    }
}

WebAppAsa/Controllers/GuessNrController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppAsa.Controllers
{
    public class GuessNrController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebAppAsa/Controllers/HomeController.cs
 using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppAsa.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()// Get
        {
            return View();//respons
        }
        public IActionResult About()//Get
        {
            return View();//respons
        }
        public IActionResult Contact()//post
        {
            return View();//respons
        }
        public IActionResult Portfolio()//Get
        {
            return View();//respons
        }

    }
}

WebAppAsa/Views/Doctor/CheckFever.cshtml
@{
    ViewData["Title"] = "CheckFever";
}

<div class="container">
    <div class="wrapper">
        <h2>Doctor Vader IOT checking out you bodytemprature</h2>
        <h3>CheckFever</h3>
        <form asp-action="CheckFever" asp-controller="Doctor" method="post">

            <input type="number" name="temp" value="" placeholder="Enter your body temperature" min="32" max="43" />
            <button type="submit">Send</button>

            <p>
                @if (ViewBag.Msg != null)
                {@ViewBag.Msg}
            </p>
        </form>
    </div>
</div>

@if (ViewBag.tempMsg != null)
{
    <p>Temp result: @ViewBag.tempMsg</p>
    
}

WebAppAsa/Views/Doctor/FeverCheck.cshtml
@{
    ViewData["Title"] = "FeverCheck";
}

<div class="container">
    <h2>Doctor Vader IOT checking out you bodytemprature</h2>
    <div class="wrapper">

        <h3>Fever Check</h3>
        <form asp-action="FeverCheck" asp-controller="Doctor" method="post">

            <input type="number" name="temp" value="" placeholder="Enter your body temperature" min="32" max="43" step="0.1" />
            <button type="submit">Submit</button>

            <p>
                @if (ViewBag.Msg != null)
                {@ViewBag.Msg}
            </p>
        </form>
    </div>
</div>

@if (ViewBag.tempMsg != null)
{
    <p>Temp result: @ViewBag.tempMsg</p>
    
}

WebAppAsa/Views/Game/GuessingGame.cshtml
@{
    ViewData["Title"] = "GuessingGame";
}

<h1>Guessing game</h1>

<div class="wrapper">
    <p>Guess a number between 1 and 100.</p>
    <p>Good Luck</p>
    <div class="card">
        <form asp-action="GuessingGame" asp-controller="Game" method="post">

            <input type="number" name="userGuess" value="" placeholder="Enter a number between 1 and 100 number" min="1" max="101" />
            <br />
            <br />
            <button class="gameButton" type="submit">Submit</button>
            <br />
            <p>
                @if (ViewBag.Msg != null)
                {@ViewBag.Msg}
            </p>

            <p>
                @if (ViewBag.Rnd != null)
                {@ViewBag.Rad}
            </p>
        </form>
        <br />
        <form asp-action="Reset" asp-controller="Game" method="get">
            <button class="resetbutton">Reset</button>
            <br />
        </form>
    </div>
</div>

WebAppAsa/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<section class="wrapper">
    <h1>About... My CV</h1>
    <article class="card">
        <h3>Kronofogden, Växjö 2018-08-27-2018-12-28</h3>
        <p>
            Ambulerande tjänsteman. Handlägger och registrerar ärenden, kundkontakter och andra
            myndighetskontakter via telefon och e-post. Hantering av inkommande post och returer.
        </p>
    </article>
    <article class="card">
        <h3>Arbetsförmedlingen, Växjö 2016-08-15-2018-04-30</h3>
        <p>
            Assistent. Varierande arbetsuppgifter som, posthantering, registrering och registervård i
            AIS. ringa upp kund inför olika uppdrag, assistera vid informations möten samt uppdatera
            säkerhetspärmarna. Vägleder kunder på direkt service med Bank-ID och ett stöd i verksamheten
            och vara behjälplig för alla kollegor och kunder.
        </p>
    </article>
    <article class="card">
        <h3>Tjänsteman(20170301) </h3>
        <p>
            Ett EU-projekt, UngKOMP som drivs av arbetsförmedlingen.
            Kontakt med arbetsgivare och sökande samt administrera i AIS, MS office. Genomför
            uppföljningar, inskrivnings samtal och studiebesök. Deltar i friskvården i samarbete med
            idrottskliniken och Växjö kommun. Ett stort stöd i verksamheten.
        </p>
    </article>
    <article class="card">
        <h3>Svenska Migrationscenter, Växjö 2014-2016.</h3>
        <p>
            Registrerar personer som har utvandrat från Sverige från 1800- talet och framåt. Från
            riksarkivet, svar digital som har många kyrkoförsamligars kyrkoböcker skannade digitalt.
            Registrerar in i Emiweb. Skannar in negativ glasplåtar från tidigt 1900-tal. Lokalvård och
            behjälplig med IT-miljön.
        </p>
    </article>
    <article class="card">
        <h3>Mackens företagscenter, Växjö, 2012.</h3>
        <p>
            Projektledare (50%). Administrationsarbete, marknadsföring och koordinering av utbildningspraktik.
            Informatör på mässor och föreläsare. Genomföra nätverksträffar i form av
            frukostmöten med praktikdeltagare. Startade ekonomiskförening “Hantverkarnas hus”.
        </p>
    </article>
    <article class="card">
        <h3>Arbete och Välfärd, Växjö kommun 2012.</h3>
        <p>
            Undervisade i kommunikativ svenska för en invandrargrupp (50%).
        </p>
    </article>
    <article class="card">
        <h3>John Bauer Gymnasiet, Växjö 2011.</h3>
        <p>
            John Bauer Gymnasiet, IT-Lärare Undervisa i datorkunskap och teknisk kommunikation,
            projektledare, projektarbete för åk 3, mentor åk 1 och betygsättare.
        </p>
    </article>
    <article class="card">
        <h3>Lokaltidningen Alvesta, Annonsproducent, 2010.</h3>
        <p>
            Producera och redigera annonser. Kundbokningar och varit ute hos kunder, vid försäljning.
        </p>
    </article>
    <article class="card">
        <h3>IST, Växjö Testare (Timanställning), 2009.</h3>
        <p>
            Testning av applikation, Extens, i Sybase SQL Anywhere 11. Både för Norge, Sverige och
            Danmark.
        </p>
    </article>
    <article class="card">
        <h3>IST, Växjö, Supporttekniker, 2000- 2008.</h3>
        <p>
            Kundsupport via telefon, mail och webb. Utbildningar internt och externt.
            Skriva utbildningsmaterial och teknisk dokumentation. Test av applikationerna Extens och
            Dexter i Sybase SQL Anywhere och Oracle miljö och databasvård. Skyddsombud arbete som
            dokumentera och skriva systematiskt arbetsmiljöarbete.
        </p>
    </article>
    <article class="card">
        <h3>Växjö kommun, 1999.</h3>
        <p>
            It-tekniker Växjö kommun: (Skolnätet), utbildare. Konfigurerade/installerade datorer,
            administration på 2000 server. Utbildare i Officepaketet och internet för ITIS, ett projekt i
            Växjö kommun. (För lärare och rektorer)
        </p>

    </article>
</section>

WebAppAsa/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}


<h1>Contact</h1>
<div class="wrapper">
    <section class="card">
        <p>Name: Åsa Jonsson</p>
        <p>Phone: 012-345 6789 </p>
    </section>

</div>

WebAppAsa/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Welcome...</h1>
<div class="wrapper">
    <div class="card">
        <h2>...to the dark side</h2>
        <h2>Do I have to remind you?</h2>
        <h5>WE HAVE COOKIES</h5>
    </div>
</div>

WebAppAsa/Views/Home/Portfolio.cshtml
@{
    ViewData["Title"] = "Portfolio";
}

<h1>Portfolio</h1>

WebAppAsa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Åsa Jomsson" ´ />

    <title>My First MVC</title>
    <link href="~/Css/Styles.css" rel="stylesheet" />
    @*Drag and drop Awesome...*@
</head>
<body>
    <header class="header-nav">
        <h1>LOGO</h1>
        <nav>
            <ul>
                <li><a asp-action="About" asp-controller="Home">About</a></li>
                <li><a asp-action="Contact" asp-controller="Home">Contact</a></li>
                <li><a asp-action="Portfolio" asp-controller="Home">Portfolio</a></li>
                <li><a asp-action="FeverCheck" asp-controller="Doctor">Doctor Vader</a></li>
                <li><a asp-action="GuessingGame" asp-controller="Game">Guessing Game</a></li>
                <li><a asp-action="Index" asp-controller="Home">Going back to index</a></li>
            </ul>
        </nav>
    </header>
    <div class="container">@*Think of it as main-container*@
        @RenderBody()@* Reder body view body content here*@
    </div>
    <footer><p>&copy; Åsa Jonsson @DateTime.Now.Year</p></footer>

</body>
</html>